import Link from "next/link";
import { FiArrowUpRight, FiBriefcase, FiGlobe, FiMail } from "react-icons/fi";

const people = [
  { initials: "AM", name: "Amara Mensah", role: "Founder & Strategy", focus: "Career systems, partnerships, and the long view.", color: "#b8d8d5" },
  { initials: "RK", name: "Rohan Kapoor", role: "Product & Engineering", focus: "Making complex career decisions feel simple.", color: "#9fc4d8" },
  { initials: "SL", name: "Sofia Laurent", role: "Community Director", focus: "Building rooms where useful conversations happen.", color: "#d9c49a" },
  { initials: "DN", name: "Daniel Nwosu", role: "Research Lead", focus: "Finding signal in roles, skills, and markets.", color: "#c9b9d8" },
];

export default function TeamPage() {
  return (
    <main data-theme="team" className="min-h-screen bg-[var(--background)] text-[var(--foreground)]">
      <section className="border-b border-[var(--borders)] bg-[var(--navbar)] px-6 py-14 md:px-12 md:py-20"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-center justify-between gap-4 text-xs font-black uppercase tracking-[0.2em] text-[var(--primary-accent)]"><span>People / Local employers</span><span className="text-[var(--secondary-text)]">Built around your community</span></div><div className="mt-20 grid gap-12 lg:grid-cols-[1fr_0.55fr] lg:items-end"><div><h1 className="max-w-4xl text-5xl font-black leading-[0.95] tracking-tight md:text-8xl">Know the people who <span className="text-[var(--primary-accent)]">hire nearby.</span></h1><p className="mt-6 max-w-xl text-base leading-relaxed text-[var(--secondary-text)]">Meet the researchers, community builders, and employer partners helping local talent find local work.</p></div><div className="border-l border-[var(--borders)] pl-6"><FiGlobe className="text-[var(--primary-accent)]" size={25} /><p className="mt-5 text-2xl font-black">4 local lenses.</p><p className="mt-1 text-sm text-[var(--secondary-text)]">One shared standard: make nearby work easier to find.</p></div></div></div></section>
      <section className="mx-auto max-w-7xl px-6 py-10 md:px-12 md:py-16"><div className="mb-10 flex items-end justify-between gap-5 border-b border-[var(--borders)] pb-5"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[var(--primary-accent)]">The directory</p><h2 className="mt-2 text-3xl font-black md:text-5xl">Different lenses, one table.</h2></div><span className="hidden text-xs font-bold text-[var(--secondary-text)] md:block">Available for thoughtful questions</span></div><div className="grid gap-x-6 gap-y-10 md:grid-cols-2">{people.map((person) => <article key={person.name} className="group grid grid-cols-[88px_1fr] gap-5 border-b border-[var(--borders)] pb-8"><div className="flex h-[88px] w-[88px] items-center justify-center text-xl font-black" style={{ backgroundColor: person.color, color: "var(--navbar)" }}>{person.initials}</div><div><p className="text-xs font-black uppercase tracking-[0.16em] text-[var(--primary-accent)]">{person.role}</p><h3 className="mt-2 text-2xl font-black group-hover:text-[var(--primary-accent)]">{person.name}</h3><p className="mt-3 text-sm leading-relaxed text-[var(--secondary-text)]">{person.focus}</p><button type="button" className="mt-5 inline-flex items-center gap-2 text-xs font-black text-[var(--foreground)]"><FiMail size={14} /> Start a conversation</button></div></article>)}</div></section>
      <section className="border-t border-[var(--borders)] bg-[var(--light-accent)] px-6 py-12 md:px-12"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 md:flex-row md:items-center"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[var(--primary-accent)]">Work with us</p><h2 className="mt-2 text-3xl font-black">Bring a useful perspective.</h2></div><Link href="/community-hub" className="inline-flex items-center gap-2 text-sm font-black text-[var(--primary-accent)]">Meet the wider community <FiArrowUpRight size={16} /></Link></div></section>
      <footer className="flex flex-col justify-between gap-3 px-6 py-8 text-xs font-bold text-[var(--secondary-text)] md:flex-row md:px-12"><span><FiBriefcase className="mr-2 inline" size={14} /> Career-Ignite</span><Link href="/" className="hover:text-[var(--foreground)]">Back to home</Link></footer>
    </main>
  );
}
